# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.24.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/leandroquevedo/Documents/Projects/C++/cpp-fire

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/leandroquevedo/Documents/Projects/C++/cpp-fire

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/opt/homebrew/Cellar/cmake/3.24.2/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/opt/homebrew/Cellar/cmake/3.24.2/bin/cpack --config ./CPackSourceConfig.cmake /Users/leandroquevedo/Documents/Projects/C++/cpp-fire/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.24.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.24.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/leandroquevedo/Documents/Projects/C++/cpp-fire/CMakeFiles /Users/leandroquevedo/Documents/Projects/C++/cpp-fire//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/leandroquevedo/Documents/Projects/C++/cpp-fire/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fire

# Build rule for target.
fire: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fire
.PHONY : fire

# fast build rule for target.
fire/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/build
.PHONY : fire/fast

#=============================================================================
# Target rules for targets named fire_lint

# Build rule for target.
fire_lint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fire_lint
.PHONY : fire_lint

# fast build rule for target.
fire_lint/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire_lint.dir/build.make CMakeFiles/fire_lint.dir/build
.PHONY : fire_lint/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f lib/raylib-5.0/CMakeFiles/uninstall.dir/build.make lib/raylib-5.0/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) $(MAKESILENT) -f lib/raylib-5.0/raylib/CMakeFiles/raylib.dir/build.make lib/raylib-5.0/raylib/CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f lib/raylib-5.0/raylib/external/glfw/src/CMakeFiles/glfw.dir/build.make lib/raylib-5.0/raylib/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f lib/raylib-5.0/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build.make lib/raylib-5.0/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

# target to build an object file
cmake_pch_arm64.hxx.pch:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/cmake_pch_arm64.hxx.pch
.PHONY : cmake_pch_arm64.hxx.pch

# target to preprocess a source file
cmake_pch_arm64.hxx.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/cmake_pch_arm64.hxx.i
.PHONY : cmake_pch_arm64.hxx.i

# target to generate assembly for a file
cmake_pch_arm64.hxx.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/cmake_pch_arm64.hxx.s
.PHONY : cmake_pch_arm64.hxx.s

src/app.o: src/app.cpp.o
.PHONY : src/app.o

# target to build an object file
src/app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/app.cpp.o
.PHONY : src/app.cpp.o

src/app.i: src/app.cpp.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/object.o: src/object.cpp.o
.PHONY : src/object.o

# target to build an object file
src/object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/object.cpp.o
.PHONY : src/object.cpp.o

src/object.i: src/object.cpp.i
.PHONY : src/object.i

# target to preprocess a source file
src/object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/object.cpp.i
.PHONY : src/object.cpp.i

src/object.s: src/object.cpp.s
.PHONY : src/object.s

# target to generate assembly for a file
src/object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/object.cpp.s
.PHONY : src/object.cpp.s

src/quadtree.o: src/quadtree.cpp.o
.PHONY : src/quadtree.o

# target to build an object file
src/quadtree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/quadtree.cpp.o
.PHONY : src/quadtree.cpp.o

src/quadtree.i: src/quadtree.cpp.i
.PHONY : src/quadtree.i

# target to preprocess a source file
src/quadtree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/quadtree.cpp.i
.PHONY : src/quadtree.cpp.i

src/quadtree.s: src/quadtree.cpp.s
.PHONY : src/quadtree.s

# target to generate assembly for a file
src/quadtree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/quadtree.cpp.s
.PHONY : src/quadtree.cpp.s

src/quadtree_dummy.o: src/quadtree_dummy.cpp.o
.PHONY : src/quadtree_dummy.o

# target to build an object file
src/quadtree_dummy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/quadtree_dummy.cpp.o
.PHONY : src/quadtree_dummy.cpp.o

src/quadtree_dummy.i: src/quadtree_dummy.cpp.i
.PHONY : src/quadtree_dummy.i

# target to preprocess a source file
src/quadtree_dummy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/quadtree_dummy.cpp.i
.PHONY : src/quadtree_dummy.cpp.i

src/quadtree_dummy.s: src/quadtree_dummy.cpp.s
.PHONY : src/quadtree_dummy.s

# target to generate assembly for a file
src/quadtree_dummy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/quadtree_dummy.cpp.s
.PHONY : src/quadtree_dummy.cpp.s

src/quadtree_grid.o: src/quadtree_grid.cpp.o
.PHONY : src/quadtree_grid.o

# target to build an object file
src/quadtree_grid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/quadtree_grid.cpp.o
.PHONY : src/quadtree_grid.cpp.o

src/quadtree_grid.i: src/quadtree_grid.cpp.i
.PHONY : src/quadtree_grid.i

# target to preprocess a source file
src/quadtree_grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/quadtree_grid.cpp.i
.PHONY : src/quadtree_grid.cpp.i

src/quadtree_grid.s: src/quadtree_grid.cpp.s
.PHONY : src/quadtree_grid.s

# target to generate assembly for a file
src/quadtree_grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/quadtree_grid.cpp.s
.PHONY : src/quadtree_grid.cpp.s

src/solver.o: src/solver.cpp.o
.PHONY : src/solver.o

# target to build an object file
src/solver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/solver.cpp.o
.PHONY : src/solver.cpp.o

src/solver.i: src/solver.cpp.i
.PHONY : src/solver.i

# target to preprocess a source file
src/solver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/solver.cpp.i
.PHONY : src/solver.cpp.i

src/solver.s: src/solver.cpp.s
.PHONY : src/solver.s

# target to generate assembly for a file
src/solver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/solver.cpp.s
.PHONY : src/solver.cpp.s

src/spawner.o: src/spawner.cpp.o
.PHONY : src/spawner.o

# target to build an object file
src/spawner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/spawner.cpp.o
.PHONY : src/spawner.cpp.o

src/spawner.i: src/spawner.cpp.i
.PHONY : src/spawner.i

# target to preprocess a source file
src/spawner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/spawner.cpp.i
.PHONY : src/spawner.cpp.i

src/spawner.s: src/spawner.cpp.s
.PHONY : src/spawner.s

# target to generate assembly for a file
src/spawner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fire.dir/build.make CMakeFiles/fire.dir/src/spawner.cpp.s
.PHONY : src/spawner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... fire_lint"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... fire"
	@echo "... glfw"
	@echo "... raylib"
	@echo "... cmake_pch_arm64.hxx.pch"
	@echo "... cmake_pch_arm64.hxx.i"
	@echo "... cmake_pch_arm64.hxx.s"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/object.o"
	@echo "... src/object.i"
	@echo "... src/object.s"
	@echo "... src/quadtree.o"
	@echo "... src/quadtree.i"
	@echo "... src/quadtree.s"
	@echo "... src/quadtree_dummy.o"
	@echo "... src/quadtree_dummy.i"
	@echo "... src/quadtree_dummy.s"
	@echo "... src/quadtree_grid.o"
	@echo "... src/quadtree_grid.i"
	@echo "... src/quadtree_grid.s"
	@echo "... src/solver.o"
	@echo "... src/solver.i"
	@echo "... src/solver.s"
	@echo "... src/spawner.o"
	@echo "... src/spawner.i"
	@echo "... src/spawner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

