name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target: [desktop, web]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          useCloudCache: true
          useLocalCache: false
          cmakeVersion: "^3.24.0"
          ninjaVersion: "^1.11.0"

      - name: Setup Emscripten
        if: matrix.target == 'web'
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.51

      - name: Configure
        run: cmake --preset=${{ matrix.target }}-release

      - name: Build
        run: cmake --build ./build/${{ matrix.target }} --target=all
