name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        target: [desktop, web]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev libglu1-mesa-dev

      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          useCloudCache: true
          useLocalCache: false
          cmakeVersion: "^3.24.0"
          ninjaVersion: "^1.11.0"

      - name: Setup Emscripten
        if: matrix.target == 'web'
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.51
      - name: Export Emscripten environment (Unix)
        if: matrix.target == 'web' && matrix.os != 'windows-latest'
        run: |
          export EMSDK_ROOT=$EMSDK/upstream/emscripten
          export EMSDK_INCLUDE_ROOT=$EMSDK/upstream/emscripten/system/include
      - name: Export Emscripten environment (Windows)
        if: matrix.target == 'web' && matrix.os == 'windows-latest'
        run: |
          $env:EMSDK_ROOT = $env:EMSDK/upstream/emscripten
          $env:EMSDK_INCLUDE_ROOT = $env:EMSDK/upstream/emscripten/system/include

      - name: Configure
        run: cmake --preset=${{ matrix.target }}-release

      - name: Build
        run: cmake --build ./build/${{ matrix.target }} --target=all
